Repository Egomination/quela, pull requests merged in 2019-04, with the labels that each got.

#13 Redesign in the Shell
  android/gradle.properties
  lib/bloc/auth/auth.dart
  lib/bloc/auth/bloc.dart
  lib/bloc/auth/state.dart
  lib/bloc/doctor/bloc.dart
  lib/bloc/patient/bloc.dart
  lib/bloc/staff/bloc.dart
  lib/bloc/staff/event.dart
  lib/bloc/staff/staff.dart
  lib/main.dart
  lib/models/doctor.dart
  lib/models/patient.dart
  lib/pages/doctor/doctor_page.dart
  lib/pages/login/mock_main.dart
  lib/pages/login/mock_splash.dart
  lib/pages/patient/dashboard_body.dart
  lib/pages/patient/dashboard_builder.dart
  lib/pages/patient/patient_info.dart
  lib/pages/patient/patient_page.dart
  lib/pages/staff/create_patient.dart
  lib/pages/staff/staff_page.dart
  lib/pages/staff/update_patient_data.dart
  lib/widgets/info_bar.dart
  lib/widgets/voip.dart
  pubspec.yaml
Labels: Beta Release, Feature Enhancement

#15 Percent 50
  android/app/src/main/res/drawable/launch_background.xml
  lib/widgets/voip.dart
Labels: Beta Release, Feature Enhancement

#17 Bugs in the Horizonxx
  lib/bloc/doctor/bloc.dart
  lib/bloc/doctor/event.dart
  lib/bloc/patient/bloc.dart
  lib/bloc/patient/event.dart
  lib/bloc/staff/staff.dart
  lib/models/doctor.dart
  lib/models/patient.dart
  lib/pages/doctor/dashboard_body.dart
  lib/pages/doctor/doctor_dashboard.dart
  lib/pages/doctor/doctor_page.dart
  lib/pages/doctor/doctor_patient.dart
  lib/pages/doctor/patient_graph.dart
  lib/pages/patient/dashboard_body.dart
  lib/pages/patient/patient_page.dart
  lib/widgets/voip.dart
  pubspec.yaml
Labels: Beta Release, Feature Enhancement, New Feature

#18 Theming
  lib/pages/doctor/doctor_dashboard.dart
  lib/pages/doctor/doctor_page.dart
  lib/pages/doctor/doctor_patient.dart
  lib/pages/doctor/patient_graph.dart
  lib/pages/patient/dashboard_body.dart
  lib/pages/patient/dashboard_builder.dart
  lib/pages/patient/patient_info.dart
  lib/pages/patient/patient_page.dart
  lib/theme.dart
  lib/widgets/info_bar.dart
  lib/widgets/voip.dart
Labels: Feature Enhancement
