Repository Egomination/quela, pull requests merged in 2019-03, with the labels that each got.

#5 Feature/voip
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  lib/bloc/patient_dashboard_bloc.dart
  lib/pages/patient/patient_page.dart
  lib/pages/patient/voip.dart
  lib/utils/random_string.dart
  lib/widgets/voip_signaling.dart
  pubspec.yaml
Labels: Alpha Release, New Feature

#6 Feature/Login Page
  android/app/build.gradle
  android/app/google-services.json
  android/build.gradle
  android/gradle.properties
  assets/q-logo.png
  lib/bloc/patient_dashboard_bloc.dart
  lib/main.dart
  lib/pages/login/login_form.dart
  lib/pages/login/login_page.dart
  lib/pages/login/mock_main.dart
  lib/pages/patient/dashboard_builder.dart
  lib/pages/patient/patient_page.dart
  lib/pages/patient/voip.dart
  lib/utils/auth.dart
  pubspec.yaml
Labels: Alpha Release, New Feature

#8 Feature/voip
  lib/bloc/patient_dashboard_bloc.dart
  lib/main.dart
  lib/models/patient.dart
  lib/pages/patient/dashboard_body.dart
  lib/pages/patient/dashboard_builder.dart
  lib/pages/patient/patient_info_bar.dart
  lib/pages/patient/patient_page.dart
  lib/pages/patient/voip.dart
  lib/widgets/voip_signaling.dart
Labels: Alpha Release, Feature Enhancement

#9 Authentication Logic with Bloc
  lib/bloc/auth/auth.dart
  lib/bloc/auth/auth_block.dart
  lib/bloc/auth/event.dart
  lib/bloc/auth/state.dart
  lib/bloc/login/event.dart
  lib/bloc/login/login_block.dart
  lib/bloc/login/state.dart
  lib/bloc/patient_dashboard_bloc.dart
  lib/main.dart
  lib/pages/login/login_form.dart
  lib/pages/login/login_page.dart
  lib/pages/login/mock_main.dart
  lib/pages/login/mock_splash.dart
  lib/pages/patient/dashboard_builder.dart
  lib/pages/patient/patient_page.dart
  lib/utils/auth.dart
  pubspec.yaml
Labels: Alpha Release, Feature Enhancement

#10 Alpha Release
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  android/gradle.properties
  assets/q-logo.png
  lib/bloc/auth/auth.dart
  lib/bloc/auth/auth_block.dart
  lib/bloc/auth/event.dart
  lib/bloc/auth/state.dart
  lib/bloc/bloc.dart
  lib/bloc/login/event.dart
  lib/bloc/login/login_block.dart
  lib/bloc/login/state.dart
  lib/bloc/patient_dashboard_bloc.dart
  lib/main.dart
  lib/models/patient.dart
  lib/pages/auth/login.dart
  lib/pages/login/login_form.dart
  lib/pages/login/login_page.dart
  lib/pages/login/mock_main.dart
  lib/pages/login/mock_splash.dart
  lib/pages/patient/alarms.dart
  lib/pages/patient/bottombar.dart
  lib/pages/patient/card.dart
  lib/pages/patient/dashboard.dart
  lib/pages/patient/dashboard_body.dart
  lib/pages/patient/dashboard_builder.dart
  lib/pages/patient/mock_data.dart
  lib/pages/patient/patient_info_bar.dart
  lib/pages/patient/patient_page.dart
  lib/pages/patient/voip.dart
  lib/utils/hex_code.dart
  lib/utils/random_string.dart
  lib/widgets/bottom_navbar.dart
  lib/widgets/voip_signaling.dart
  pubspec.yaml
Labels: Alpha Release
